<?php
namespace shandyrov\shards\assetbundles;

use yii\web\AssetBundle;
use yii\web\View;

class AdminShardsHeadAsset extends AssetBundle
{

    public $sourcePath = '@vendor/shandyrov/yii2-shards-asset/dist';

    public $css = [
        'styles/all.css',
        'styles/icon.css',
        'styles/bootstrap.min.css',
        'styles/shards-dashboards.1.1.0.min.css',
        'styles/extras.1.1.0.min.css',
    ];

    public $cssOptions = [];

    public $jsOptions = ['position' => View::POS_HEAD];

    public $js = [
        //'scripts/buttons.js',
    ];

    public $depends = [];


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}

