<?php
namespace shandyrov\shards\assetbundles;

use yii\web\AssetBundle;
use yii\web\View;
use Yii;

class AdminShardsEndAsset extends AssetBundle
{

    public $sourcePath = '@vendor/shandyrov/yii2-shards-asset/dist';

    public $css = [];

    public $cssOptions = [];

    public $jsOptions = ['position' => View::POS_END];

    public $js = [

        'scripts/jquery-3.3.1.min.js',
        'scripts/popper.min.js',
        'scripts/bootstrap.min.js',
        //'scripts/Chart.min.js',
        'scripts/shards.min.js',
        'scripts/jquery.sharrre.min.js',
        'scripts/extras.1.1.0.min.js',
        //'scripts/shards-dashboards-chart.1.1.0.js',
        //'scripts/app/app-blog-overview.1.1.0.js',
    ];

    public $depends = [
        'shandyrov\shards\assetbundles\AdminShardsHeadAsset'
    ];


    public function init()
    {
        if (Yii::$app->request->pathInfo == 'admin/dashboard') {
            //die('ok');
        }
        parent::init(); // TODO: Change the autogenerated stub
    }
}
